name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, readline, ldap, msgpack, igbinary, redis, swoole, memcached, pcov
          coverage: none

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-posix

      - name: Check PHP Syntax
        run: |
          find src -name "*.php" -print0 | xargs -0 -n1 php -l
